specVersion: "4.0"
metadata:
  name: com.gavdilabs.config
type: application
framework:
  name: SAPUI5
  version: "1.136.1"
  libraries:
    - name: sap.m
    - name: sap.f
    - name: sap.ui.core
    - name: themelib_sap_horizon
builder:
  resources:
    excludes:
      - "test/e2e/**"
  customTasks:
    - name: ui5-tooling-transpile-task
      afterTask: replaceVersion
    - name: ui5-task-zipper
      afterTask: generateVersionInfo
      configuration:
        archiveName: "config"
        additionalFiles:
          - xs-app.json
server:
  customMiddleware:
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        watchPath: "webapp"
    - name: ui5-middleware-simpleproxy
      afterMiddleware: compression
      mountPath: /RadarService
      configuration:
        baseUri: "http://localhost:4004/odata/v4/radar"
